name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Mona"
    - name: Trigger deploy
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        curl --insecure https://$DEPLOY_HOST/deploy/bot?secret=$DEPLOY_KEY

  test:
    name: Test multi-container action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run postgres
      run: cd ./action-compose && docker-compose up -d
    - name: test pg connection
      run: ./action-compose/test.sh


